Repository equinor/libres, pull requests merged in 2019-02, with the labels that each got.

#492 Use pointer to const for all the matrices in the analysis update
  lib/analysis/analysis_module.cpp
  lib/analysis/bootstrap_enkf.cpp
  lib/analysis/cv_enkf.cpp
  lib/analysis/fwd_step_enkf.cpp
  lib/analysis/null_enkf.cpp
  lib/analysis/sqrt_enkf.cpp
  lib/analysis/std_enkf.cpp
  lib/include/ert/analysis/analysis_module.hpp
  lib/include/ert/analysis/analysis_table.hpp
  lib/include/ert/analysis/cv_enkf.hpp
  lib/include/ert/analysis/std_enkf.hpp
Labels: in progress

#506 Update travis with mutltibuild
  .libecl_version
  .travis.yml
  config.sh
  lib/CMakeLists.txt
  lib/analysis/enkf_linalg.cpp
  lib/enkf/tests/data/config/analysis_load_site_config_osx
  requirements.txt
Labels: in progress, ready for review

#513 Secure abs calls
  lib/analysis/bootstrap_enkf.cpp
  lib/analysis/cv_enkf.cpp
  lib/analysis/enkf_linalg.cpp
  lib/analysis/fwd_step_enkf.cpp
  lib/analysis/modules/rml_enkf.c
  lib/enkf/custom_kw.cpp
  lib/enkf/data_ranking.cpp
  lib/enkf/enkf_analysis.cpp
  lib/enkf/enkf_obs.cpp
  lib/enkf/enkf_plot_gendata.cpp
  lib/enkf/enkf_util.cpp
  lib/enkf/field.cpp
  lib/enkf/field_config.cpp
  lib/enkf/field_trans.cpp
  lib/enkf/gen_data.cpp
  lib/enkf/gen_kw.cpp
  lib/enkf/meas_data.cpp
  lib/enkf/misfit_ensemble.cpp
  lib/enkf/misfit_ranking.cpp
  lib/enkf/obs_data.cpp
  lib/enkf/obs_vector.cpp
  lib/enkf/ranking_table.cpp
  lib/enkf/summary.cpp
  lib/enkf/summary_obs.cpp
  lib/enkf/surface.cpp
  lib/enkf/time_map.cpp
  lib/enkf/trans_func.cpp
  lib/enkf/value_export.cpp
  lib/include/ert/enkf/ranking_common.hpp
  lib/job_queue/tests/job_status_test.cpp
  lib/res_util/matrix.cpp
  lib/res_util/matrix_lapack.cpp
  lib/res_util/matrix_stat.cpp
  lib/res_util/regression.cpp
  lib/res_util/subst_func.cpp
  lib/res_util/tests/ert_util_matrix.cpp
  lib/res_util/tests/ert_util_matrix_lapack.cpp
  lib/rms/rms_tagkey.cpp
  lib/sched/sched_kw_compdat.cpp
  python/tests/res/enkf/export/test_export_join.py
  python/tests/res/enkf/export/test_misfit_collector.py
Labels: ready for review

#515 Expose ITER as magic string
  lib/enkf/run_arg.cpp
  python/tests/res/enkf/test_runpath_list_dump.py
  test-data/local/snake_oil_no_data/snake_oil_GEO_ID.ert
Labels: in progress

#517 Add std:: to isnan() function call
  lib/enkf/value_export.cpp
Labels: in progress
